apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-raju-cluster
  region: us-east-2
nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    ssh: # use existing EC2 key
      publicKeyName: eks-raju
  - name: ng-mixed
    minSize:  2
    maxSize:  3
    instancesDistribution:
      maxPrice: 0.2
      instanceType: ["t2.small", "t3.small"]
      onDemandBasedCapacity:  0   #This will make sure that we dont start with any ondemand instances
      onDemandPercentageAboveBaseCapacity:  50  #Saying 50 means, 50% of instances will be ondemand and 50% will be spot instances
    ssh: # use existing EC2 key
      publicKeyName: eks-raju