apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-raju-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    ssh: # use existing EC2 key
      #allow:  true
      publicKeyName: eks-raju
	cloudWatch:
	  clusterLogging:
	    enableTypes:  ["api", "audit", "authenticatator"] /["*"]